//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asmerald.Generate.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asmerald.Generate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DbType;CSharpType;AsmeraldType
        ///bool;System.Boolean;BooleanColumn
        ///boolean;System.Boolean;BooleanColumn
        ///bit(1);System.Boolean;BooleanColumn
        ///tinyint;System.SByte;IntegerColumn
        ///tinyint unsigned;System.Byte;ByteColumn
        ///smallint;System.Int16;IntegerColumn
        ///year;System.Int16;IntegerColumn
        ///int;System.Int32;IntegerColumn
        ///integer;System.Int32;IntegerColumn
        ///smallint unsigned;System.Int32;IntegerColumn
        ///mediumint;System.Int32;IntegerColumn
        ///bigint;System.Int64;LongColumn
        ///int unsigned;System.Int64;LongColumn
        ///i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string mariadb_type_mapping {
            get {
                return ResourceManager.GetString("mariadb_type_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DbType;CSharpType;AsmeraldType
        ///bigint;Int64;LongColumn
        ///binary;Byte[];ByteArrColumn
        ///bit;Boolean;BooleanColumn
        ///char;String;StringColumn
        ///date;DateTime;DateTimeColumn
        ///datetime;DateTime;DateTimeColumn
        ///datetime2;DateTime;DateTimeColumn
        ///datetimeoffset;DateTimeOffset;DateTimeOffsetColumn
        ///decimal;Decimal;DecimalColumn
        ///varbinary;Byte[];ByteArrColumn
        ///float;Double;DecimalColumn
        ///image;Byte[];ByteArrColumn
        ///int;Int32;IntegerColumn
        ///money;Decimal;DecimalColumn
        ///nchar;String;StringColumn
        ///ntext;String;StringCol [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string mssql_type_mapping {
            get {
                return ResourceManager.GetString("mssql_type_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DbType;CSharpType;AsmeraldType
        ///bool;System.Boolean;BooleanColumn
        ///boolean;System.Boolean;BooleanColumn
        ///bit(1);System.Boolean;BooleanColumn
        ///tinyint;System.SByte;IntegerColumn
        ///tinyint unsigned;System.Byte;ByteColumn
        ///smallint;System.Int16;IntegerColumn
        ///year;System.Int16;IntegerColumn
        ///int;System.Int32;IntegerColumn
        ///integer;System.Int32;IntegerColumn
        ///smallint unsigned;System.Int32;IntegerColumn
        ///mediumint;System.Int32;IntegerColumn
        ///bigint;System.Int64;LongColumn
        ///int unsigned;System.Int64;LongColumn
        ///i [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string mysql_type_mapping {
            get {
                return ResourceManager.GetString("mysql_type_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DbType;CSharpType;AsmeraldType
        ///BFILE;Byte[];ByteArrColumn
        ///BLOB;Byte[];ByteArrColumn
        ///CHAR;String;StringColumn
        ///CLOB;String;StringColumn
        ///DATE;DateTime;DateTimeColumn
        ///FLOAT;Decimal;DecimalColumn
        ///INTEGER;Decimal;DecimalColumn
        ///INTERVAL YEAR TO MONTH;Int32;IntegerColumn
        ///INTERVAL DAY TO SECOND;TimeSpan;TimeSpanColumn
        ///LONG;String;StringColumn
        ///LONG RAW;Byte[];ByteArrColumn
        ///NCHAR;String;StringColumn
        ///NCLOB;String;StringColumn
        ///NUMBER;Decimal;DecimalColumn
        ///NVARCHAR2;String;StringColumn
        ///RAW;Byte[];ByteArrC [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string oracle_type_mapping {
            get {
                return ResourceManager.GetString("oracle_type_mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DbType;CSharpType;AsmeraldType
        ///boolean;bool;BooleanColumn
        ///smallint;short;IntegerColumn
        ///integer;int;IntegerColumn
        ///bigint;long;LongColumn
        ///real;float;DecimalColumn
        ///double precision;double;DecimalColumn
        ///numeric;decimal;DecimalColumn
        ///money;decimal;DecimalColumn
        ///text;string;StringColumn
        ///character varying;string;StringColumn
        ///character;string;StringColumn
        ///citext;string;StringColumn
        ///json;string;StringColumn
        ///jsonb;string;StringColumn
        ///xml;string;StringColumn
        ///uuid;Guid;GuidColumn
        ///bytea;byte[];ByteArrCo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string postgresql_type_mapping {
            get {
                return ResourceManager.GetString("postgresql_type_mapping", resourceCulture);
            }
        }
    }
}
