/*
 This file was automatically generated by Asmerald.Generate library / executable.
 It is not recommened to make manual changes in this file as any changes to this file will be overwritten when the next generation happens.
 In case you need modifications please refer to adjusting the generation process itself.
 This is possible by creating your own executable project and referencing or forking Asmerald.Generate library / executable.
*/

namespace test
{
    public partial class dbo
    {
        public static StProc_GetProductDesc_withparameters GetProductDesc_withparameters(System.Decimal @PID) => new StProc_GetProductDesc_withparameters(@PID);
        public class StProc_GetProductDesc_withparameters : Asmerald.StoredProcedures.IStoredProcedure
        {
            public string Name() => "GetProductDesc_withparameters";

            private readonly decimal @PID;

            public StProc_GetProductDesc_withparameters(System.Decimal @PID)
            {
                this.@PID = @PID;
            }

            public List<(string, object)> GetParameters()
            {
                return new List<(string, object)>()
                {
                    ("@PID", @PID)
                };
            }
        }
    }
}
